name: Update WordPress Plugin

on:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-plugin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: alleyinteractive/action-update-wordpress-plugin@v1.2.1
      with:
        plugin-file: 'wp-page-cache-control.php'
        upgrade-npm-dependencies: "true"
